chore(build,karma): update 'ktest-all' for webpack
- 'ktest-all' is now simply a find-all cmd piped into 'ktest'
- 'ktest'
  - now handles all the logic of:
    - splitting files (from either from stdin, or from positional
      args) into smaller lists
    - generating appropriate '*.karma.shim.js' files
    - running 'parallel' cmd split across multiple '--shimFile=...'
      args
- 'ktest-helpers'
  - helper functions for use by 'ktest'
- 'ktest-helpers.bats'
  - tests for 'calc_lines_per_file'
- 'karma.shim.tpl.js'
  - a template file, meant for injection a series of
    'require("...");'-statements (performed by 'ktest')
- add './karma' subdir
  - mv 'karma.shim.js' -> './karma/karma.shim.default.js'

chore(build,karma): use 'karma.shim.default.js' if no
'--shimFile=...' specified by 'karma start'

chore(build,karma): use 'ktest-all' for 'npm run test'

diff --git a/bin/ktest b/bin/ktest
--- a/bin/ktest
+++ b/bin/ktest
@@ -5,26 +5,15 @@ if [ -z "${WX2_ADMIN_WEB_CLIENT_HOME}" ]; then
     exit 1
 fi
 
-function ex_usage {
-    echo "Run a one-off karma single-run test for a given karma spec file."
-    echo ""
-    echo "usage: $(basename "$0") [--help|-h|-?] [--debug] <karma_spec_file>"
-    echo ""
-    echo "ex. single karma spec file"
-    echo "  $(basename "$0") trial.service.spec.js"
-    echo ""
-    echo "ex. all spec files in the parent dir"
-    echo "  $(basename "$0") ../*.spec.js"
-    echo ""
-    echo "ex. all spec files found under the './app' dir"
-    echo "  find ./app -iname \\*spec.js | $(basename "$0")"
-}
-
-# early out if looking for usage
-if [[ "$1" == "--help" || "$1" == "-h" || "$1" == "-?" ]]; then
-    ex_usage
+if ! type parallel >/dev/null 2>&1; then
+    >&2 echo "Error: no 'parallel' program found, please install 'parallel' first. (Run 'brew install parallel' on Mac, or see: http://www.gnu.org/software/parallel/ )"
     exit 1
 fi
+
+source "${WX2_ADMIN_WEB_CLIENT_HOME}/bin/include/core-helpers"
+source "${WX2_ADMIN_WEB_CLIENT_HOME}/bin/include/ktest-helpers"
+
+# ----------
 
 # otherwise collect '--*' args for passing through to gulp
 pass_through_opts=
@@ -46,31 +35,67 @@ set -- "${args[@]}"
 # remap stdin to positional params
 set -- "${1:-$(</dev/stdin)}" "${@:2}"
 
-cache_dir=$WX2_ADMIN_WEB_CLIENT_HOME/.cache
-
-# tidy up cache dir (in case previous runs exit badly)
-rm -f "$cache_dir"/tmp.ktest.*
-
-flist=$(mktemp "$cache_dir"/tmp.ktest.XXXXX)
+# ----------
+# compose the raw file list
+temp_dir=$(mk_temp_dir_for_ktest)
+flist=$(mktemp "$temp_dir/flist.XXXXX")
 
 # shellcheck disable=SC2068
 # generate a file list
+fname=
 for arg in $@; do
-    ls -1 "$(pwd)/$arg" >> "$flist" 2>/dev/null
+    if [[ "$arg" = /* ]]; then
+        fname="$arg"
+    else
+        fname="$(pwd)/$arg"
+    fi
+    ls -1 "$fname" >> "$flist" 2>/dev/null
 done
 
-# use it for a test run
-exit_status=
-if [ -s "$flist" ]; then
-    # shellcheck disable=SC2086
-    gulp karma-custom --files-from="$flist" $pass_through_opts
-    exit_status=$?
-fi
+# ----------
+# split the raw file list
+shim_tpl="${WX2_ADMIN_WEB_CLIENT_HOME}/karma/karma.shim.tpl.js"
+total_specs=$(wc -l "$flist" | awk '{print $1;}')
+lines_per_file=$(calc_lines_per_file $total_specs)
 
+# list all spec files, splitting list into roughly equal sizes
+sort "$flist" \
+    | split -l $lines_per_file - "$temp_dir/flist-split."
+
+# ----------
+# process split lists
+# - process them into shim files
+# - compose a string of multiple '--shimFile=...' args
+shim_file_args=""
+for i in "$temp_dir"/flist-split.*; do
+    printf "%-48s %s\n" "[INFO] Running: making list for injection... " "${i}.require-list"
+    mk_require_list_file "${i}" > "${i}.require-list"
+
+    karma_shim_file="${WX2_ADMIN_WEB_CLIENT_HOME}/karma/$(basename $i).karma.shim.js"
+    printf "%-45s %s\n" "[INFO] Running: making temp karma shim files... " "$karma_shim_file"
+    inject_require_list_file "${i}.require-list" "$shim_tpl" > "$karma_shim_file"
+
+    shim_file_args="$shim_file_args --shimFile=$karma_shim_file"
+done
+
+# ----------
+# run tests in gnu 'parallel'
+# loading the correct webpack config requires 'npm_lifecycle_event' be set
+export npm_lifecycle_event=test
+
+# run 'karma' at the project root dir
+pushd ${WX2_ADMIN_WEB_CLIENT_HOME} > /dev/null
+set -x
+parallel karma start ::: $shim_file_args
+exit_status=$?
+set +x
+popd > /dev/null
+
+# ----------
 # tidy up
-custom_karma_conf_file="${WX2_ADMIN_WEB_CLIENT_HOME}/test/karma-unit-custom.$(basename "$flist").js"
-rm -f "$custom_karma_conf_file"
-rm -f "$flist"
+set -x
+rm -rf "$temp_dir"
+rm -f "${WX2_ADMIN_WEB_CLIENT_HOME}"/karma/flist-split.*
+set +x
 
-# pass back exit status from gulp command
 exit $exit_status
