chore(build): install 'nvm' and 'node 6' as-needed
chore(build): rename functions in 'setup.sh'

- 'install_parallel_as_needed' -> 'install_gnu_parallel'
- 'npm_install' -> 'install_npm_deps_via_npm'
- 'yarn_install' -> 'install_npm_deps_via_yarn'

chore(build): shellcheck lint cleanups in 'setup.sh'

diff --git a/bin/include/setup-helpers b/bin/include/setup-helpers
--- a/bin/include/setup-helpers
+++ b/bin/include/setup-helpers
@@ -20,25 +20,28 @@ function is_installed {
     return $?
 }
 
-# install GNU Parallel for known used OS's
-function install_parallel_as_needed {
-    set -x
-    if ! is_installed "parallel"; then
-        if is_installed "brew"; then
-            brew install parallel                  # Mac (as of Yosemite)
-        elif is_installed "dnf"; then
-            sudo dnf install -y parallel           # Fedora (as of F23)
-        elif is_installed "yum"; then
-            sudo yum install -y parallel           # CentOS (as of CentOS 7)
-        elif is_installed "apt-get"; then
-            sudo apt-get update                    # Ubuntu (as of 14.04)
-            sudo apt-get install -y parallel
-        else
-            >&2 echo "[ERROR] ${FUNCNAME[0]} package manager on this OS is not supported."
-            return 1
-        fi
+# install GNU parallel for known used OS's
+function install_gnu_parallel {
+    # Mac (as of Yosemite)
+    if is_installed "brew"; then
+        brew install parallel
+        return $?
+    # Fedora (as of F23)
+    elif is_installed "dnf"; then
+        sudo dnf install -y parallel
+        return $?
+    # CentOS (as of CentOS 7)
+    elif is_installed "yum"; then
+        sudo yum install -y parallel
+        return $?
+    # Ubuntu (as of 14.04)
+    elif is_installed "apt-get"; then
+        sudo apt-get update
+        sudo apt-get install -y parallel
+        return $?
     fi
-    set +x
+    >&2 echo "[ERROR] ${FUNCNAME[0]} package manager on this OS is not supported."
+    return 1
 }
 
 # quietly validate checksums
